notifications:
  email: false
language: shell

jobs:
  include:
    - os: windows
env:
  global:
#    - CIBW_SKIP="cp27-* cp35-* *-win_amd64"
    - CIBW_BUILD="cp36-win_amd64"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}"
    - CIBW_BEFORE_BUILD="bash build.sh"
before_install:
  - choco install python --version 3.8.0
  - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
install:
  - /c/Python38/python.exe -m pip install cibuildwheel
script:
  - /c/Python38/python.exe -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse

# after_success:
#   - |
#     if [[ $TWINE_PASSWORD  ]]; then
#       python3 -m pip install twine
#       python3 -m twine upload --skip-existing wheelhouse/*.whl
#     fi
