notifications:
  email: false
language: shell
jobs:
  include:
    - os: windows
before_install:
  - choco install python --version=3.8
  - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

install:
  - /c/Python38/python.exe setup.py bdist_wheel