notifications:
  email: false
language: shell

jobs:
  include:
    # linux build
    - services: docker
      language: python
      env:
        - PYTHON=python3
        - CIBW_BEFORE_BUILD="$PYTHON -m pip install Cython"
    # macos build
    - os: osx
      env:
        - PYTHON=python3
        - CIBW_BEFORE_BUILD="$PYTHON -m pip install Cython"
    # win_amd64 build
    - os: windows
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        - CIBW_BUILD="*-win_amd64"
        - PLATFORM_OPTION="-A x64"
        - CIBW_BEFORE_BUILD="$PYTHON -m pip install Cython; bash build.sh"
        - PYTHON=/c/Python38/python.exe
    # win32 build
    - os: windows
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        - CIBW_BUILD="*-win32"
        - CIBW_BEFORE_BUILD="$PYTHON -m pip install Cython; bash build.sh"
        - PYTHON=/c/Python38/python.exe
    - language: python
      arch: arm64
      install:
      script:
        - python3 -m pip install -U setuptools pip wheel Cython
        - python3 setup.py sdist
        # without --no-cache:
        # [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/3a'
        - python3 -m pip install --no-cache dist/*.tar.gz
        - pytest
      after_success:
          - |
            if [[ $TWINE_PASSWORD  ]]; then
              python3 -m pip install --no-cache twine
              python3 -m twine upload --skip-existing dist/*
            fi        

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_SKIP="cp27-* cp35-*"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}"

install:
  - $PYTHON -m pip install cibuildwheel

script:
  - $PYTHON -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse

after_success:
  - |
    if [[ $TWINE_PASSWORD  ]]; then
      $PYTHON -m pip install twine
      $PYTHON -m twine upload --skip-existing wheelhouse/*.whl
    fi
