notifications:
  email: false
language: shell

jobs:
  include:
    - os: windows
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        global:
            - CIBW_BUILD="*-win_amd64"
            - PLATFORM_OPTION=-A Win32
            - CIBW_BEFORE_BUILD="bash build.sh"
            - PYTHON=/c/Python38/python.exe
    - os: windows
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        global:
            - CIBW_BUILD="*-win32"
            - CIBW_BEFORE_BUILD="bash build.sh"
            - PYTHON=/c/Python38/python.exe

env:
  global:
    - CIBW_SKIP="cp27-* cp35-*"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}"
    - PYTHON=python3
install:
  - $PYTHON -m pip install cibuildwheel
script:
  - $PYTHON -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse

after_success:
  - |
    if [[ $TWINE_PASSWORD  ]]; then
      python3 -m pip install twine
      python3 -m twine upload --skip-existing wheelhouse/*.whl
    fi
