notifications:
  email: false
language: python
jobs:
  include:
    - os: windows
before_install:
  - choco install cmake.portable
  - choco install git.portable
install:
  - ./build.sh
  - /c/Python38/python.exe -m pip install .
