language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
install:
  - python -m pip install .
script:
  - pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "aF3uMJTqFvn5m4+LqMHBGEOQ+jRB5NtKqoY9V2BDExlOfZU2PhtHiA8G0ExUpTGXn343tJ0l+LO1TKAgYYOQ9+mrjoUuEx5H+De9Dr8ZftNxmeWkE493Z49yPqOXYRHkVoId/viZqtZjZN4vem4JIRBKkXdbQ6loE+fizr3KRgE6IKe5hyUUCHer8dHOs9L1OBTQftsBU0pWyBMkisvyVQP9GRUUHBUDozFo9MTP38K/OSd2RfnAxr8cL91JxFfIFg0HrQK0AOwRZQ1Z4FPGcnOOkSM25limQMkbPYGNCsm1oDfzwNNH0ojdrD0QPuGxr3FFf6hfS5LTxZQOqKhD+F5vYQ/fTHj/GF29PED5AmXnXj3cCxdsD2FveXo/QF/yjN629KXzVEegCp00Jc+uBJmA2FOZpw85MbvreMIvxWyfyJLGjp7qz7JQM7d8u4H2VCXoa48glSBbw2FDQZzfH05ea8EkNfs+Vd5ysDzIfVKpuQ3G+BtAxwkKcIYG0aknjZhiUMhgXJ6wHapCPVd6wLnk7LdUxelbgFYiidntpHZAqglocp+kkQOC5xXTMQdAGFBKWMVZTQsF/GKid03Ey3ZJLtlc0XQvD9Hx6GtOkZAztqIdJGu20gEjGk0G7FWLGMCpnpHt6WO+Bb3TkPP9ekE1wU0Cwa9bCPxt23C1RbU="
  distributions: "sdist bdist_wheel"
  skip_existing: true