language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build
install:
  - python -m pip install .
script:
  - pytest
deploy:
  provider: pypi
  user: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDc3MDRiYzYyLTYxODYtNGM3YS04ZDM2LTVkOWUwZjQwY2I0ZQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgmf0ergF3GywsnvBvenZJyuLccFLHrdrGPuJ916STmyc"
