name: Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - name: Checkout Repository And Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Install Pydivsufsort And Other Dependencies
        run: |
          pip install cython cmake numpy
          ./build.sh
          python -m pip install .
        shell: bash
      - name: Run Unit Tests
        run: pytest
        shell: bash
